// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = (function(cfg) {
    this.graph = false;
    this.cfg = {};
    this.ohmygraph = require('ohmygraph');
    this.jref = this.ohmygraph.jref;
    this.loader = function() {
      if (this.cfg.opts.debug != null) {
        return console.log("no loader specificied");
      }
    };
    this.init_graph = function(graph) {
      var omg;
      omg = this.ohmygraph.create(graph, {
        baseurl: "https://api.github.com",
        verbose: 2
      });
      omg.init.client();
      console.log("graph initialized \\o/");
      return this.graph = omg.graph;
    };
    this.start = function(cfg) {
      this.cfg = this.cfg;
      if (this.cfg.opts.debug != null) {
        console.dir(JSON.parse(JSON.stringify(this.cfg)));
      }
      if (this.cfg.opts.debug != null) {
        this.ohmygraph.jref.debug = true;
      }
      this.ohmygraph.jref.reftoken = '@ref';
      this.ohmygraph.jref.pathtoken = '@';
      this.cfg.embed = this.ohmygraph.jref.resolve(this.cfg.embed);
      if (this.cfg.opts.debug != null) {
        console.dir(this.cfg.embed);
      }
      this.init_graph(this.cfg.embed.rest);
      return this.init_tags();
    };
    this.init_tags = function() {
      var ref, results, tag, uicomponent;
      ref = this.cfg.embed.ui;
      results = [];
      for (tag in ref) {
        uicomponent = ref[tag];
        uicomponent.tagname = tag;
        if (this.cfg.opts.debug != null) {
          console.log("mounting tag " + tag);
        }
        uicomponent.tag = riot.mount(tag, {
          me: uicomponent,
          app: this
        });
        if (uicomponent.tag.length) {
          results.push(uicomponent.tag = uicomponent.tag[0]);
        } else {
          results.push(void 0);
        }
      }
      return results;
    };
    return this;
  }).call({});

}).call(this);
